# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TL2b4URlwrPlnAbWOQ8SWRtwGVP6lZu2
"""



"""# Sección nueva"""